# Generated by Django 5.1.7 on 2025-03-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="user",
        ),
        migrations.AlterField(
            model_name="patient",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
